name: 'PIPELINE'

on:
  push:
    branches:
    - '**'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run install packages
      run: |
        yarn install
    - name: Run lint
      run: |
        yarn lint
    - name: Run Tests
      run: |
        yarn test